### ISSUE TITLE
GroupMod message should support selection_method and fields

### ISSUE THREAD

**Issue by tnqn** [antrea-io/libOpenflow#42]
To implement DSR in Antrea (https://github.com/antrea-io/antrea/issues/5025), we need to use `hash` selection method and specify `fields` when installing a group for a service with DSR enabled (See https://github.com/antrea-io/antrea/issues/5025#issuecomment-1578787479 for reason). But the library doesn't support these fields.

**Comment by wenyingd** [comment]
I think we should firstly define a new struct for "Netronome selection_method" (https://github.com/openvswitch/ovs/blob/903294cde6e19b3eccefee13875f83b5ada2774c/include/openflow/netronome-ext.h#L36C8-L36C39), then append it into GroupMod.Properties (https://github.com/antrea-io/libOpenflow/blob/main/openflow15/group.go#L62)

A valid "Netronome selection_method" can be constructed reffering to https://github.com/openvswitch/ovs/blob/master/lib/ofp-group.c#L1210
